### ISSUE TITLE
image pull policy should be IfNotPresent

### ISSUE THREAD

**Issue by yankay** [hwameistor/drbd-adapter#6]
https://github.com/hwameistor/drbd-adapter/blob/cbd922a4ac726bada9fc63db6d37e58f4605f87f/helm/drbd-adapter/templates/drbd-adapter.yaml#L19

image pull policy should be IfNotPresent , it's more common

**Comment by alexzhc** [comment]
Good point, will make it configurable in values.yaml with `IfNotPresent` as default
