### ISSUE TITLE
Installed 8.x version in Ubuntu 

### ISSUE THREAD

**Issue by yankay** [hwameistor/drbd-adapter#8]
![企业微信截图_16620056423041](https://user-images.githubusercontent.com/1469319/187830167-967592d9-28b5-477c-a532-58b3465ac6e6.png)

**Comment by alexzhc** [comment]
Ubuntu kernels come with in-house drbd 8.x. Unless it is unloaded by `rmmod` or disabled at boot, drbd 9.x cannot overwrite a loaded kernel module.

Will seek a graceful solution from the official dkms.deb scripts

**Comment by alexzhc** [comment]
Further investigation shows that per 'cat /proc/drbd' the loaded version is exactly 9.x, but modinfo still displays the old 8.x version. 

Changing drop_location to `/lib/modules/$(uname -r)/updates/dkms/drbd/` solves the issue. 

Will fix in next release
