### ISSUE TITLE
drbd-utils will not be installed properly during installation

### ISSUE THREAD

**Issue by FloatXD** [hwameistor/drbd-adapter#82]
drbd-utils will not be installed properly during installation

**Comment by peng9808** [comment]
https://github.com/hwameistor/drbd-adapter/pull/83  If you have time, you can help test and verify the feasibility.

**Comment by peng9808** [comment]
> #83 If you have time, you can help test and verify the feasibility.



> drbd-utils will not be installed properly during installation

https://github.com/hwameistor/drbd-adapter/pull/83  If you have time, you can help test and verify the feasibility.

**Comment by peng9808** [comment]
> drbd-utils will not be installed properly during installation

https://github.com/hwameistor/drbd-adapter/pull/83  If you have time, you can help test and verify the feasibility.
